from .BaiduTranslate import NODE_CLASS_MAPPINGS as BAIDU_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as BAIDU_NODE_DISPLAY_NAME_MAPPINGS
from .DictionaryNodes import NODE_CLASS_MAPPINGS as DICT_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as DICT_NODE_DISPLAY_NAME_MAPPINGS

WEB_DIRECTORY = "."

NODE_CLASS_MAPPINGS = {**BAIDU_NODE_CLASS_MAPPINGS, **DICT_NODE_CLASS_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**BAIDU_NODE_DISPLAY_NAME_MAPPINGS, **DICT_NODE_DISPLAY_NAME_MAPPINGS}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY']
